[project]
name = "fastapi-app"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "fastapi>=0.124.4",
    "numpy>=2.2.6",
    "sentence-transformers>=5.2.0",
    "uvicorn>=0.38.0",
]
 